# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on: [ push, pull_request, workflow_dispatch ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project
          
  deploy-to-dev:
    runs-on: ubuntu-18.04
    name: Deploy to Dev
    needs: [build]
    environment: "Development"
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'
      - uses: gradle/gradle-build-action@v2
        with:
          arguments: build
          
#   deploy-to-test:
#     runs-on: ubuntu-18.04
#     name: Deploy to Testing
#     needs: [deploy-to-dev]
#     environment: "testing"
#     steps:
#       - name: Running test deployment
#         run: |
#           echo Deploying to testing...
#           sleep 10s

#   deploy-to-staging:
#     runs-on: ubuntu-18.04
#     name: Deploy to Staging
#     needs: [deploy-to-test]
#     environment: "111:test_staging-env"
#     if: ${{ github.ref == 'refs/heads/master' }}
#     steps:
#       - name: Running staging deployment
#         run: |
#           echo Deploying to staging...
#           sleep 10s
          
  deploy-to-prod:
    runs-on: ubuntu-18.04
    name: Deploy to Production
    environment: "Production"
    needs: [build]
    if: ${{ github.ref == 'refs/heads/master' }}
    steps: 
      - name: Running production deployment
        run: |
          echo Deploying to production...
